apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: blog-app
spec:
  host: blog-app-blog-app.apps-crc.testing
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: proxy
    weight: 100