apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
    - name: http
      nodePort: 30080
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      nodePort: 30443
      port: 443
      targetPort: 8443
      protocol: TCP
